using Content.Shared._salemstation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._salemstation
{
    [GenerateTypedNameReferences]
    public sealed partial class TribunalWindow : DefaultWindow
    {
        public event Action<bool>? OnVotePressed;

        public TribunalWindow()
        {
            RobustXamlLoader.Load(this);

            GuiltyButton.OnPressed += _ => OnVotePressed?.Invoke(true);
            InnocentButton.OnPressed += _ => OnVotePressed?.Invoke(false);
        }

        public void UpdateState(TribunalBoundUserInterfaceState state)
        {
            PrisonerLabel.Text = $"Accused: {state.PrisonerName}";
            PhaseLabel.Text = $"Current Phase: {state.CurrentPhase}";
            TimerLabel.Text = $"Time Remaining: {(int) state.TimeRemaining.TotalMinutes}:{state.TimeRemaining.Seconds:D2}";

            GuiltyButton.Text = $"Guilty ({state.GuiltyVotes})";
            InnocentButton.Text = $"Innocent ({state.InnocentVotes})";

            var isVotingPhase = state.CurrentPhase == "Voting";
            GuiltyButton.Disabled = !isVotingPhase;
            InnocentButton.Disabled = !isVotingPhase;
        }
    }
}
